# Generated by Django 5.2 on 2025-08-13 13:56

import datetime
import django.db.models.deletion
import office.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_team_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_granularity_minutes', models.PositiveSmallIntegerField(default=15)),
                ('rounding_mode', models.CharField(choices=[('nearest', 'Nearest (四捨五入)'), ('up', 'Ceil (切り上げ)'), ('down', 'Floor (切り捨て)')], default='nearest', max_length=10)),
                ('break_template_json', models.JSONField(default=office.models.default_break_template, help_text="[{start:'HH:MM', end:'HH:MM'}, ...]")),
                ('overtime_starts_at', models.TimeField(default=datetime.time(17, 0))),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=5)),
                ('night_starts_at', models.TimeField(default=datetime.time(22, 0))),
                ('night_ends_at', models.TimeField(default=datetime.time(5, 0))),
                ('night_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=5)),
                ('weekly_holidays', models.JSONField(default=office.models.default_weekly_holidays)),
                ('custom_holidays', models.JSONField(default=office.models.empty_list)),
                ('custom_workdays', models.JSONField(default=office.models.empty_list)),
                ('piecework_defaults_json', models.JSONField(blank=True, default=office.models.empty_dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='WageContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('pay_type', models.CharField(choices=[('monthly', '月給'), ('daily', '日給'), ('hourly', '時給'), ('piecework', '出来高')], max_length=20)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hourly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('piecework_schema_json', models.JSONField(blank=True, default=office.models.empty_dict)),
                ('override_company_policy', models.BooleanField(default=False)),
                ('custom_overtime_rate_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_night_rate_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_contracts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wage_contracts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'user', 'effective_from'], name='office_wage_company_b0a1a6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('monthly_salary__isnull', False), ('pay_type', 'monthly')), models.Q(('daily_wage__isnull', False), ('pay_type', 'daily')), models.Q(('hourly_wage__isnull', False), ('pay_type', 'hourly')), ('pay_type', 'piecework'), _connector='OR'), name='wagecontract_amount_by_type')],
            },
        ),
    ]
