# Generated by Django 5.2 on 2025-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_team_teammember'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=end-of-month, 1-28'),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='pay_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=end-of-month, 1-28'),
        ),
        migrations.AddField(
            model_name='companypayrollpolicy',
            name='pay_month_offset',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='companypayrollpolicy',
            constraint=models.UniqueConstraint(fields=('company',), name='uniq_company_policy'),
        ),
    ]
