# Generated by Django 5.2 on 2025-07-26 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_team_teammember'),
        ('schedule', '0004_schedule_resource'),
        ('site_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('locked', 'ロック（締め後）')], default='draft', max_length=16, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reports', to='companies.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_reports', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'チーム日報',
                'verbose_name_plural': 'チーム日報一覧',
                'ordering': ['-date', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('locked', 'ロック（締め後）')], default='draft', max_length=16, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reports', to='companies.company', verbose_name='会社')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reports', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('source_team_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_personal_reports', to='reports.teamreport', verbose_name='生成元チーム日報')),
            ],
            options={
                'verbose_name': '個人日報',
                'verbose_name_plural': '個人日報一覧',
                'ordering': ['-date', 'user__id'],
            },
        ),
        migrations.CreateModel(
            name='TeamReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='メモ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_report_entries', to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.teamreport', verbose_name='チーム日報')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_report_entries', to='site_app.site', verbose_name='現場')),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_report_entries', to='schedule.workcategory', verbose_name='作業内容')),
            ],
            options={
                'verbose_name': 'チーム日報明細',
                'verbose_name_plural': 'チーム日報明細一覧',
                'ordering': ['report', 'member__id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_from_source', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='メモ')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.personalreport', verbose_name='個人日報')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_report_entries', to='site_app.site', verbose_name='現場')),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_report_entries', to='schedule.workcategory', verbose_name='作業内容')),
                ('source_team_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to_personal_entries', to='reports.teamreportentry', verbose_name='生成元チーム明細')),
            ],
            options={
                'verbose_name': '個人日報明細',
                'verbose_name_plural': '個人日報明細一覧',
                'ordering': ['report_id'],
            },
        ),
        migrations.CreateModel(
            name='ClosingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_month', models.DateField(verbose_name='対象月(1日を格納)')),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_closings', to=settings.AUTH_USER_MODEL, verbose_name='締め実行者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_periods', to='companies.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': '締め期間',
                'verbose_name_plural': '締め期間一覧',
                'indexes': [models.Index(fields=['company', 'year_month'], name='reports_clo_company_e212f0_idx')],
                'unique_together': {('company', 'year_month')},
            },
        ),
        migrations.AddIndex(
            model_name='teamreport',
            index=models.Index(fields=['company', 'team', 'date'], name='reports_tea_company_ab8e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamreport',
            index=models.Index(fields=['status'], name='reports_tea_status_7f6ade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamreport',
            unique_together={('company', 'team', 'date')},
        ),
        migrations.AddIndex(
            model_name='personalreport',
            index=models.Index(fields=['company', 'user', 'date'], name='reports_per_company_875c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='personalreport',
            index=models.Index(fields=['status'], name='reports_per_status_172d64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalreport',
            unique_together={('company', 'user', 'date')},
        ),
        migrations.AddIndex(
            model_name='teamreportentry',
            index=models.Index(fields=['report'], name='reports_tea_report__900f99_idx'),
        ),
        migrations.AddIndex(
            model_name='teamreportentry',
            index=models.Index(fields=['member'], name='reports_tea_member__8acb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='teamreportentry',
            index=models.Index(fields=['site'], name='reports_tea_site_id_664cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='personalreportentry',
            index=models.Index(fields=['report'], name='reports_per_report__ecd47d_idx'),
        ),
        migrations.AddIndex(
            model_name='personalreportentry',
            index=models.Index(fields=['site'], name='reports_per_site_id_b4da4c_idx'),
        ),
    ]
