# Generated by Django 5.2 on 2025-08-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_personalreportentry_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_personal_reports', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='personalreport',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('pending', '承認待ち'), ('submitted', '提出済み'), ('locked', 'ロック（締め後）')], default='draft', max_length=16, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='teamreport',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('pending', '承認待ち'), ('submitted', '提出済み'), ('locked', 'ロック（締め後）')], default='draft', max_length=16, verbose_name='ステータス'),
        ),
    ]
