# Generated by Django 5.2 on 2025-08-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_teamreport_approved_at_teamreport_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamreport',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='teamreport',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='personalreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_personal_reports', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
    ]
