# Generated by Django 5.2 on 2025-06-13 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_invitecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='URL セーフ & シャーディングしやすい主キー', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='現場名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('general_contractor_name', models.CharField(blank=True, max_length=100, verbose_name='ゼネコン名')),
                ('manager_name', models.CharField(blank=True, max_length=50, verbose_name='所長名')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='所長の電話番号')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='作業開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='作業終了日')),
                ('memo', models.TextField(blank=True, help_text='現場に関する注意点や特記事項など', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='companies.company', verbose_name='会社')),
            ],
        ),
    ]
