# Generated by Django 5.2 on 2025-06-22 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_invitecode'),
        ('site_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作業内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workCategorys', to='companies.company', verbose_name='会社 (テナント)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='URL セーフ & シャーディングしやすい主キー', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('end_time', models.DateTimeField(verbose_name='終了日時')),
                ('schedule_type', models.CharField(choices=[('personal', '個人'), ('team', 'チーム'), ('resource', 'リソース')], default='personal', max_length=20, verbose_name='予定の種類')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='companies.company', verbose_name='会社 (テナント)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('members', models.ManyToManyField(blank=True, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='site_app.site', verbose_name='現場')),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedule.workcategory', verbose_name='作業内容')),
            ],
        ),
    ]
