# Generated by Django 5.2 on 2025-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
