# Generated by Django 5.2 on 2025-07-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_team_teammember'),
        ('schedule', '0002_workcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teams',
            field=models.ManyToManyField(related_name='schedules', to='companies.team', verbose_name='対象チーム'),
        ),
    ]
