# Generated by Django 5.2 on 2025-07-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('schedule', '0003_schedule_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='resources.resource', verbose_name='対象リソース'),
        ),
    ]
