# Generated by Django 5.2 on 2025-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='icon',
            field=models.ImageField(blank=True, help_text='グループチャットのアイコン画像。DMでは通常使わない', null=True, upload_to='chat_icons/', verbose_name='アイコン画像'),
        ),
    ]
