# Generated by Django 5.2 on 2025-05-23 04:39

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, help_text='ソート可能 ULID（時系列順で自然に整列）', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
