# Generated by Django 5.2 on 2025-05-23 04:51

import chat.fields
import chat.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=chat.fields.ULIDField(default=chat.utils.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
