# Generated by Django 5.2 on 2025-05-30 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='招待時刻')),
                ('is_participated', models.BooleanField(default=False, verbose_name='参加済み')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.conversation', verbose_name='会話')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='招待したユーザー')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_invitations', to=settings.AUTH_USER_MODEL, verbose_name='招待されたユーザー')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'invitee'), name='unique_invitation_per_conversation')],
            },
        ),
    ]
