# Generated by Django 5.2 on 2025-06-25 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_invitecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='URL セーフ & シャーディングしやすい主キー', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='チーム名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='companies.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム一覧',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'リーダー'), ('member', 'メンバー')], default='member', max_length=20, verbose_name='役割')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='参加日時')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.team', verbose_name='所属チーム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チームメンバー',
                'verbose_name_plural': 'チームメンバー一覧',
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
