# Generated by Django 5.2 on 2025-07-14 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_team_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='companies.company', verbose_name='会社 (テナント)')),
            ],
            options={
                'verbose_name': 'リソースカテゴリ',
                'verbose_name_plural': 'リソースカテゴリ一覧',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='URL セーフ & シャーディングしやすい主キー', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('maker', models.CharField(blank=True, max_length=50, verbose_name='メーカー')),
                ('plate_no', models.CharField(blank=True, max_length=15, verbose_name='ナンバー')),
                ('capacityKg', models.PositiveIntegerField(blank=True, null=True, verbose_name='積載量(kg)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, help_text='廃車・売却時に False にして論理削除として扱う', verbose_name='稼働中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='companies.company', verbose_name='会社 (テナント)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'リソース',
                'verbose_name_plural': 'リソース一覧',
                'ordering': ['name'],
            },
        ),
    ]
