# Generated by Django 5.2 on 2025-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_post_company_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_important',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
