# Generated by Django 5.2 on 2025-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('manager', '部長'), ('member', '一般'), ('clerk', '事務員')], default='member', max_length=10),
        ),
    ]
